# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name BVAR_linear
#' @noRd
BVAR_linear <- function(Y_in, W_in, p_in, saves_in, burns_in, cons_in, trend_in, sv_in, thin_in, prior_in, hyperparam_in) {
    .Call(`_BGVAR_BVAR_linear`, Y_in, W_in, p_in, saves_in, burns_in, cons_in, trend_in, sv_in, thin_in, prior_in, hyperparam_in)
}

do_rgig1 <- function(lambda, chi, psi) {
    .Call(`_BGVAR_do_rgig1`, lambda, chi, psi)
}

#' @name gvar_stacking
#' @noRd
gvar_stacking <- function(xglobal_in, plag_in, globalpost_in, saves_in, thin_in, trend_in, eigen_in) {
    .Call(`_BGVAR_gvar_stacking`, xglobal_in, plag_in, globalpost_in, saves_in, thin_in, trend_in, eigen_in)
}

#' @name globalLik
#' @noRd
globalLik <- function(Y_in, X_in, A_in, S_in, Ginv_in, thinsaves_in) {
    .Call(`_BGVAR_globalLik`, Y_in, X_in, A_in, S_in, Ginv_in, thinsaves_in)
}

#' @name dmvnrm_arma_fast
#' @noRd
dmvnrm_arma_fast <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_BGVAR_dmvnrm_arma_fast`, x, mean, sigma, logd)
}

