# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BVAR_linear <- function(Yraw, Wraw, Exraw, lags, draws, burnin, thin, cons, trend, sv, prior, hyperparam, setting_store) {
    .Call(`_BGVAR_BVAR_linear`, Yraw, Wraw, Exraw, lags, draws, burnin, thin, cons, trend, sv, prior, hyperparam, setting_store)
}

#' @name do_rgig
#' @noRd
do_rgig1 <- function(lambda, chi, psi) {
    .Call(`_BGVAR_do_rgig1`, lambda, chi, psi)
}

#' @name gvar_stacking
#' @noRd
gvar_stacking <- function(xglobal, plag, globalpost, draws, thin, trend, eigen, verbose) {
    .Call(`_BGVAR_gvar_stacking`, xglobal, plag, globalpost, draws, thin, trend, eigen, verbose)
}

#' @name globalLik
#' @noRd
globalLik <- function(Y_in, X_in, A_in, S_in, Ginv_in, thindraws_in) {
    .Call(`_BGVAR_globalLik`, Y_in, X_in, A_in, S_in, Ginv_in, thindraws_in)
}

#' @name dmvnrm_arma_fast
#' @noRd
dmvnrm_arma_fast <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_BGVAR_dmvnrm_arma_fast`, x, mean, sigma, logd)
}

#' @name compute_irf
#' @noRd
compute_irf <- function(A_large, S_large, Ginv_large, type, nhor, thindraws, shocklist_in, save_rot, verbose) {
    .Call(`_BGVAR_compute_irf`, A_large, S_large, Ginv_large, type, nhor, thindraws, shocklist_in, save_rot, verbose)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_BGVAR_RcppExport_registerCCallable`)
})
